version: '3.8'
services:
  app:
    build: .
    env_file:
      - .env.example
    volumes:
      - ./app:/app
      - ./data:/data
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
